### ISSUE TITLE
Initial Build

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-google-analytics-source#1]
**Requirements**
- Pass in `viewId` as parameter
- Pass in `dataRanges` parameter with `startDate` defaulted to current date - 2 and `endDate` defaulted to current date - 1.
- Allow for [`Dimensions`](https://developers.google.com/analytics/devguides/reporting/core/v4/rest/v4/reports/batchGet?authuser=1#dimension) to be optionally passed in and filter results
- Allow for [`DimensionFilterClause`](https://developers.google.com/analytics/devguides/reporting/core/v4/rest/v4/reports/batchGet?authuser=1#dimensionfilterclause) to be passed in to combine dimension filters
- Allow for [`Segments`](https://developers.google.com/analytics/devguides/reporting/core/v4/rest/v4/reports/batchGet?authuser=1#segment) to be optionally passed in
- Allow for [`userSegments`](https://developers.google.com/analytics/devguides/reporting/core/v4/rest/v4/reports/batchGet?authuser=1#dynamicsegment) to be optionally passed in
- Allow for [`Cohort`](https://developers.google.com/analytics/devguides/reporting/core/v4/rest/v4/reports/batchGet?authuser=1#cohort) date to optionally be passed in

**Relevant Links**
https://github.com/google/google-api-nodejs-client/
https://developers.google.com/analytics/devguides/reporting/core/v4/basics

**Comment by beckysteele** [comment]
@RyanPnayR, I believe this is completed.  Can you confirm?
